version: '3.1'
services :
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go-server
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080