name: Continues integration and grup-project-facebook deployment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install front-end
        working-directory: front-end
        run: npm ci

      - name: Install back-end
        working-directory: back-end
        run: mvn clean install
